name: Create and publish the Docker image for Obstracts Web Staging

on:
  push:
    branches: ['main']

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}_obstracts_web_staging

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    environment: obstracts_web_staging
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.deploy
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: |
            REACT_APP_AUTH0_DOMAIN=auth.signalscorps.com
            REACT_APP_AUTH0_CLIENT_ID=gPWdgbZHOoMjaCJ6YQuYieTDs90iIgp1
            REACT_APP_API_BASE_URL=https://management.obstracts.staging.signalscorps.com/
            REACT_APP_OBSTRACTS_API_SWAGGER_URL=https://api.obstracts.staging.signalscorps.com/schema/swagger-ui/
            REACT_APP_ADMIN_URL=https://management.obstracts.staging.signalscorps.com/admin/
            REACT_APP_TAXII_SWAGGER_URL=http://taxii.obstracts.staging.signalscorps.com/schema/swagger-ui/
      - name: Generate artifact attestation
        uses: actions/attest-build-provenance@v1
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true